# 1c411d7732dd_add_approval_requests_table.py
# Purpose: Phase 5 migration — creates the generic `approval_requests` table (spec section 22
#          human-in-the-loop) and adds three new `audit_action_type` enum values used by the new
#          approval service/API (refund_request_rejected, pending_action_approved,
#          pending_action_rejected).
# Author: CloudDesk Team
# Date: 2026-09-24

"""add approval_requests table

Revision ID: 1c411d7732dd
Revises: c2a7a8e4f141
Create Date: 2026-09-24 15:09:41.349523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c411d7732dd'
down_revision: Union[str, None] = 'c2a7a8e4f141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NEW_AUDIT_ACTION_TYPES: tuple[str, ...] = (
    "refund_request_rejected",
    "pending_action_approved",
    "pending_action_rejected",
)


def upgrade() -> None:
    # New audit_action_type enum values for the Phase 5 approval workflow. Must run outside the
    # implicit DDL transaction batching issues of ALTER TYPE ... ADD VALUE by using autocommit-safe
    # IF NOT EXISTS guards (Postgres 16 permits this inside a transaction).
    for value in NEW_AUDIT_ACTION_TYPES:
        op.execute(f"ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('decided_by', sa.String(length=150), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('refund_request_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_thread_id'), 'approval_requests', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_thread_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
    # Note: Postgres does not support removing enum values (no DROP VALUE); the three
    # audit_action_type values added in upgrade() are intentionally left in place on downgrade.
